name: S4living
favicon: null
layout_spectrum: 0.20251
typography_spectrum: 0.68502
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010005'
    - '#fefdf8'
    - '#2f6ca3'
    - '#a8c6e0'
    - '#999faf'
  brandStrength: 0.625
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
