typography_spectrum: 0.253367843804881
color:
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
  brandStrength: 0.12748151645064354
  lightness: 0.38849506922997534
  saturation: 0.4875834216363728
  rhythmicContrast: 0.1624817738775164
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3706153405364603
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e45a7c56-d2f2-4dad-bb89-2ceb43bb14cf.jpg
name: S4living
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Solution 4 Living
description: Life Style Real Estate
purpose: []
