layout_spectrum: 0.20880498620681465
typography_spectrum: 0.9534429772756994
color:
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
  brandStrength: 0.4035126199014485
  lightness: 0.4289385883603245
  saturation: 0.6208485716488212
  rhythmicContrast: 0.7613420898560435
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: S4living
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Solution 4 Living
description: Life Style Real Estate
purpose: []
